name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:

  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run Unit Test
      run: go test -v ./...

  sast-scan:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: --no-fail ./...
  
  vuln-scan:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: 'fs'
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        severity: "HIGH,CRITICAL"

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'


  build-scan-push-image:
    runs-on: ubuntu-latest
    needs: [sast-scan, vuln-scan]

    env:
      REGISTRY: docker.io
      IMAGE_NAME: trihatmaja/azan-schedule
      K8S_NAMESPACE: azan-schedule

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} -f ./app/api/Dockerfile ../.
        docker build -t ${{ env.IMAGE_NAME }}:latest -f ./app/api/Dockerfile ../.
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
        format: 'sarif'
        exit-code: '0'
        output: 'trivy-results.sarif'
        severity: "HIGH,CRITICAL"
        vuln-type: 'os,library'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Push Image
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }} 
        docker push ${{ env.IMAGE_NAME }}:latest
    

  # kubernetes-deployment:
    # runs-on: ubuntu-latest
    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Set up Kubeconfig
    #   run: |
    #     mkdir -p ~/.kube
    #     echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
    #     chmod 600 ~/.kube/config

    # - name: Update image in deployment.yaml
    #   run: |
    #     sed -i "s|image:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" k8s/deployment.yaml

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/
